---

test:
  image: gcc:12-bookworm
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install -yqq cmake valgrind python3 python3-pip python3-virtualenv
    - cmake --preset dev
    - cmake --build --preset dev
    - ctest --output-junit report.xml --preset dev
    - virtualenv venv
    - source venv/bin/activate
    - pip install valgrind-codequality gcovr
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
    - ctest -T memcheck --test-dir build/dev
    - valgrind-codequality --input-file build/dev/tests/valgrind.xml --output-file valgrind.json
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      junit: build/dev/report.xml
      codequality: valgrind.json
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


fuzzy-test:
  image: silkeh/clang:15-bookworm
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install --no-install-recommends -yqq git cmake valgrind
    - cmake --preset fuzzy
    - cmake --build --preset fuzzy
    - ctest --preset fuzzy -R fuzzy --output-on-failure
