---

test:
  image: gcc:12-bookworm
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install -yqq cmake valgrind python3 python3-pip python3-virtualenv
    - cmake --preset dev
    - cmake --build --preset dev
    - ctest --output-junit report.xml --preset dev
    - ctest -T memcheck --test-dir build/dev
    - virtualenv venv
    - source venv/bin/activate
    - pip install valgrind-codequality
    - valgrind-codequality --input-file build/dev/tests/valgrind.xml --output-file valgrind.json
  artifacts:
    reports:
      junit: build/dev/report.xml
      codequality: valgrind.json


fuzzy-test:
  image: silkeh/clang:15-bookworm
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install --no-install-recommends -yqq git cmake
    - cmake --preset fuzzy
    - cmake --build --preset fuzzy
    - ctest --preset fuzzy -R fuzzy --output-on-failure
