
#pragma once


#define URC_OK 0
#define URC_ECBORINTERNALERROR 1
#define URC_EUNHANDLEDCASE 2
#define URC_EUNEXPECTEDTYPE 3
#define URC_EUNEXPECTEDTAG 4
#define URC_EUNEXPECTEDMAPKEY 5
#define URC_EUNEXPECTEDSTRINGLENGTH 6
#define URC_EUNIMPLEMENTEDURTYPE 7
#define URC_EUNKNOWNFORMAT 8
#define URC_ETAPROOTNOTSUPPORTED 9
#define URC_EBUFFERTOOSMALL 10
